spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    name: testdb
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    generate-unique-name: false


  flyway:
    enabled: true
    locations: classpath:db/migration

# App Properties
bezkoder:
    app:
      jwtCookieName: bezkoder
      jwtSecret:  ======================BezKoder=Spring===========================
      jwtExpirationMs: 86400000
